/*
This file is generated by esbuild from the sources in src/.
Do not edit it directly - edit src/main.ts and run "npm run build".
*/
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OpenInVSCodePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var nodePath = __toESM(require("path"));
var fs = __toESM(require("fs"));
var os = __toESM(require("os"));
var DEFAULT_SETTINGS = {
  executable: "",
  reuseWindow: true,
  extraArgs: "",
  debug: false
};
var SUPPORTED_EDITORS = {
  code: "VS Code",
  cursor: "Cursor",
  trae: "Trae",
  zed: "Zed",
  windsurf: "Windsurf"
};
function detectExecutable() {
  var _a, _b, _c;
  const home = os.homedir();
  const candidates = [];
  if (process.platform === "win32") {
    const localAppData = (_a = process.env.LOCALAPPDATA) != null ? _a : "";
    const programFiles = (_b = process.env["ProgramFiles"]) != null ? _b : "";
    const programFilesX86 = (_c = process.env["ProgramFiles(x86)"]) != null ? _c : "";
    const suffixes = [
      ["Microsoft VS Code", "code.cmd"],
      ["Cursor", "cursor.cmd"]
    ];
    for (const [dir, bin] of suffixes) {
      candidates.push(nodePath.join(localAppData, "Programs", dir, "bin", bin));
      candidates.push(nodePath.join(programFiles, dir, "bin", bin));
      candidates.push(nodePath.join(programFilesX86, dir, "bin", bin));
    }
    candidates.push(
      nodePath.join(localAppData, "Programs", "Microsoft VS Code", "bin", "code.cmd")
    );
  } else if (process.platform === "darwin") {
    candidates.push(
      "/usr/local/bin/code",
      "/opt/homebrew/bin/code",
      "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code",
      nodePath.join(
        home,
        "Applications",
        "Visual Studio Code.app",
        "Contents",
        "Resources",
        "app",
        "bin",
        "code"
      )
    );
  } else {
    candidates.push(
      "/usr/bin/code",
      "/usr/local/bin/code",
      "/snap/bin/code",
      "/usr/share/code/bin/code"
    );
  }
  for (const candidate of candidates) {
    if (!candidate) continue;
    try {
      if (fs.existsSync(candidate)) return candidate;
    } catch (e) {
      continue;
    }
  }
  return "code";
}
function quote(value) {
  return `"${value.replace(/"/g, '\\"')}"`;
}
function normalizeExecutable(exe) {
  if (process.platform !== "win32") return exe;
  if (!nodePath.isAbsolute(exe)) return exe;
  const base = nodePath.basename(exe);
  if (!base.toLowerCase().endsWith(".exe")) return exe;
  const dir = nodePath.dirname(exe);
  const cliName = base.slice(0, -4).toLowerCase() + ".cmd";
  const candidates = [
    nodePath.join(dir, "bin", cliName),
    nodePath.join(dir, "resources", "app", "bin", cliName)
  ];
  for (const candidate of candidates) {
    try {
      if (fs.existsSync(candidate)) return candidate;
    } catch (e) {
      continue;
    }
  }
  return exe;
}
var OpenInVSCodePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "open-current-file",
      name: "Open the current file",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) return false;
        if (!checking) void this.launch(this.absPath(file));
        return true;
      }
    });
    this.addCommand({
      id: "open-vault-folder",
      name: "Open the vault folder",
      callback: () => void this.launch(this.vaultPath())
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian.TFile)) return;
        menu.addItem(
          (item) => item.setTitle("Open in VS Code").setIcon("file-code").onClick(() => void this.launch(this.absPath(file)))
        );
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, _editor, view) => {
        const file = view == null ? void 0 : view.file;
        if (!file) return;
        menu.addItem(
          (item) => item.setTitle("Open in VS Code").setIcon("file-code").onClick(() => void this.launch(this.absPath(file)))
        );
      })
    );
    this.addRibbonIcon("file-code", "Open the current file in VS Code", () => {
      const file = this.app.workspace.getActiveFile();
      if (!file) {
        new import_obsidian.Notice("No active file.");
        return;
      }
      void this.launch(this.absPath(file));
    });
    this.addSettingTab(new OpenInVSCodeSettingTab(this.app, this));
  }
  vaultPath() {
    var _a, _b;
    const adapter = this.app.vault.adapter;
    return (_b = (_a = adapter.getBasePath) == null ? void 0 : _a.call(adapter)) != null ? _b : "";
  }
  absPath(file) {
    return nodePath.join(this.vaultPath(), file.path);
  }
  /** What the user configured, before any CLI entry point correction. */
  rawExecutable() {
    var _a;
    return ((_a = this.settings.executable) != null ? _a : "").trim() || detectExecutable();
  }
  /** What will actually be launched. */
  executable() {
    return normalizeExecutable(this.rawExecutable());
  }
  /**
   * Resolves what the configured executable actually points to.
   * Absolute paths are checked on disk, bare command names are looked up
   * on the PATH using the same environment Obsidian itself was launched with.
   * Returns the resolved path, or null when nothing could be found.
   */
  verifyExecutable(exe) {
    return new Promise((resolve) => {
      if (nodePath.isAbsolute(exe)) {
        try {
          resolve(fs.existsSync(exe) ? exe : null);
        } catch (e) {
          resolve(null);
        }
        return;
      }
      const probe = process.platform === "win32" ? `where "${exe}" 2>nul` : `command -v "${exe}" 2>/dev/null`;
      (0, import_child_process.exec)(probe, (_err, stdout) => {
        const lines = (stdout != null ? stdout : "").trim().split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
        if (!lines.length) {
          resolve(null);
          return;
        }
        const script = lines.find((line) => /\.(cmd|bat)$/i.test(line));
        resolve(script != null ? script : lines[0]);
      });
    });
  }
  async launch(target) {
    var _a;
    const args = [];
    if (this.settings.reuseWindow) args.push("-r");
    args.push(target);
    const exe = await this.resolveExecutable();
    if (!exe) {
      new import_obsidian.Notice(
        `Cannot find "${this.rawExecutable()}". Set a full absolute path in the Open in VSCode settings.`,
        15e3
      );
      return;
    }
    const extra = ((_a = this.settings.extraArgs) != null ? _a : "").trim();
    const commandLine = [quote(exe), ...args.map(quote), extra].filter(Boolean).join(" ");
    if (this.settings.debug) {
      console.log("[open-in-vscode] executable =", exe);
      console.log("[open-in-vscode] commandLine =", commandLine);
      console.log("[open-in-vscode] platform =", process.platform);
    }
    let child;
    try {
      child = (0, import_child_process.spawn)(commandLine, {
        shell: true,
        detached: true,
        stdio: this.settings.debug ? "inherit" : "ignore",
        windowsHide: true
      });
    } catch (err) {
      const message = err.message;
      new import_obsidian.Notice(`Could not start the editor: ${message}`);
      console.error("[open-in-vscode] spawn threw", err);
      return;
    }
    child.on("error", (err) => {
      new import_obsidian.Notice(`Could not start the editor: ${err.message}`);
      console.error("[open-in-vscode] spawn error", err);
    });
    if (this.settings.debug) {
      child.on("exit", (code) => {
        console.log("[open-in-vscode] child exited with code", code);
        if (code !== 0) {
          new import_obsidian.Notice(
            `Editor exited with code ${code}. On Windows 9009 usually means the executable could not be found.`,
            15e3
          );
        }
      });
    }
    child.unref();
  }
  /**
   * Returns an absolute path to something that can actually be executed,
   * or null when the configured value cannot be resolved.
   */
  async resolveExecutable() {
    const exe = this.executable();
    if (nodePath.isAbsolute(exe)) {
      try {
        return fs.existsSync(exe) ? exe : null;
      } catch (e) {
        return null;
      }
    }
    const found = await this.verifyExecutable(exe);
    if (!found) return null;
    return nodePath.isAbsolute(found) ? normalizeExecutable(found) : found;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var OpenInVSCodeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Editor executable").setDesc(
      "Leave empty to detect the editor automatically. Enter a command name such as cursor, trae, zed or windsurf, or a full absolute path."
    ).addText(
      (text) => text.setPlaceholder(`Automatic (currently ${this.plugin.executable()})`).setValue(this.plugin.settings.executable).onChange(async (value) => {
        this.plugin.settings.executable = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Reuse the existing window").setDesc("Passes -r so an already open editor window is reused instead of opening a new one.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.reuseWindow).onChange(async (value) => {
        this.plugin.settings.reuseWindow = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Extra arguments").setDesc("Optional. For example --new-window. Usually left empty.").addText(
      (text) => text.setPlaceholder("Empty").setValue(this.plugin.settings.extraArgs).onChange(async (value) => {
        this.plugin.settings.extraArgs = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Test").setDesc(
      "Resolves the configured executable and opens the active note with it. Requires a note to be open."
    ).addButton(
      (button) => button.setButtonText("Test").onClick(async () => {
        const file = this.plugin.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("Open a note first, then run the test.", 8e3);
          return;
        }
        const raw = this.plugin.rawExecutable();
        const resolved = await this.plugin.resolveExecutable();
        if (!resolved) {
          new import_obsidian.Notice(
            `Cannot resolve "${raw}". It is not on your PATH and no file exists at that path. Enter a full absolute path instead, then restart Obsidian if you just changed PATH.`,
            15e3
          );
          return;
        }
        const switched = resolved !== raw;
        const note = switched ? `Resolved to:
${resolved}

Opening the active note...` : `Using:
${resolved}

Opening the active note...`;
        new import_obsidian.Notice(note, 1e4);
        await this.plugin.launch(this.plugin.absPath(file));
      })
    );
    new import_obsidian.Setting(containerEl).setName("Debug logging").setDesc(
      "Logs the resolved command line to the developer console, and reports the exit code. Enable this when the editor does not open."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.debug).onChange(async (value) => {
        this.plugin.settings.debug = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("p", {
      text: `Vault path: ${this.plugin.vaultPath()}`,
      cls: "setting-item-description"
    });
    const editors = Object.entries(SUPPORTED_EDITORS).map(([bin, label]) => `${bin} = ${label}`).join("  \xB7  ");
    containerEl.createEl("p", {
      text: `Command names you can enter: ${editors}.`,
      cls: "setting-item-description"
    });
  }
};

/* nosourcemap */